"use client";
// import type { Metadata } from 'next'
import { Inter } from "next/font/google";
import Providers from "../../redux/store/Providers";
import LeftBar from "./../components/leftBar";
import React from "react";
import AuthWrapper from "../authWrapper";
// import { PersistGate } from 'redux-persist/integration/react'
// import { PersistGate } from 'redux-persist/es/integration/react'

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

function RootLayout({ children }: { children: React.ReactNode }) {
  return (
      <AuthWrapper>
        <div className="flex">

            <Providers>
              <LeftBar />
              {children}
            </Providers>
        </div>
      </AuthWrapper>
  );
}
export default RootLayout;
